# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)
        args: ["--profile", "black"]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        stages: [pre-push, pre-merge-commit, post-merge, pre-rebase]
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
-   repo: local
    hooks:
    -   id: coverage
        name: pytest-coverage-check
        entry: "pytest -m 'not slow' --cov=src/sca/"
        language: system
        pass_filenames: false
        always_run: true
        verbose: true
        stages: [commit]
    -   id: coverage-badge
        name: coverage-badge
        entry: "coverage-badge -fo media/coverage.svg"
        language: system
        pass_filenames: false
        always_run: true
    -   id: full-test-suite
        name: run-all-tests
        entry: "pytest --cov=src/sca/"
        language: system
        pass_filenames: false
        always_run: true
        verbose: true
        stages: [push, post-merge]
